services:
  app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - "app:/code"
  db:
    mem_limit: "16g"
    shm_size: '16gb'
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./database:/database"
      - "./data-formation:/data-formation"
      - "./data:/data"
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: '--encoding=LATIN1 --lc-collate=C --lc-ctype=C'
volumes:
  app:
    driver: local
  db:
    driver: local