services:
  app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - "app:/code"
  db:
    mem_limit: "16g"
    shm_size: '16gb'
    image: "postgres"
    volumes:
      - "./database:/database"
      - "./data-formation:/data-formation"
      - "./data:/data"
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASS}
volumes:
  app:
    driver: local
  db:
    driver: local