services:
  app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - "app:/code"
  db:
    mem_limit: "16g"
    shm_size: '16gb'
    image: "postgres"
    volumes:
      - "./database:/database"
      - "./data-formation:/data-formation"
      - "./data:/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      LANGUAGE: 'de_DE.UTF-8'
      LC_ALL: 'de_DE.UTF-8'
      LANG: 'de_DE.UTF-8'
volumes:
  app:
    driver: local
  db:
    driver: local