import xml.etree.ElementTree as ET

def parser():
    """
    Parser to all special characters
    :return: a xml Parser
    """
    parser = ET.XMLParser()
    parser.entity["Agrave"] = "À"
    parser.entity["Aacute"] = "Á"
    parser.entity["Acirc"] = "Â"
    parser.entity["Atilde"] = "Ã"
    parser.entity["Auml"] = "Ä"
    parser.entity["Aring"] = "Å"
    parser.entity["agrave"] = "à"
    parser.entity["aacute"] = "á"
    parser.entity["acirc"] = "â"
    parser.entity["atilde"] = "ã"
    parser.entity["auml"] = "ä"
    parser.entity["aring"] = "å"
    parser.entity["Egrave"] = "È"
    parser.entity["Eacute"] = "É"
    parser.entity["Ecirc"] = "Ê"
    parser.entity["Euml"] = "Ë"
    parser.entity["egrave"] = "è"
    parser.entity["eacute"] = "é"
    parser.entity["ecirc"] = "ê"
    parser.entity["euml"] = "ë"
    parser.entity["Igrave"] = "Ì"
    parser.entity["Iacute"] = "Í"
    parser.entity["Icirc"] = "Î"
    parser.entity["Iuml"] = "Ï"
    parser.entity["igrave"] = "ì"
    parser.entity["iacute"] = "í"
    parser.entity["icirc"] = "î"
    parser.entity["iuml"] = "ï"
    parser.entity["Ograve"] = "Ò"
    parser.entity["Oacute"] = "Ó"
    parser.entity["Ocirc"] = "Ô"
    parser.entity["Otilde"] = "Õ"
    parser.entity["Ouml"] = "Ö"
    parser.entity["ograve"] = "ò"
    parser.entity["oacute"] = "ó"
    parser.entity["ocirc"] = "ô"
    parser.entity["otilde"] = "õ"
    parser.entity["ouml"] = "ö"
    parser.entity["Ugrave"] = "Ù"
    parser.entity["Uacute"] = "Ú"
    parser.entity["Ucirc"] = "Û"
    parser.entity["Uuml"] = "Ü"
    parser.entity["ugrave"] = "ù"
    parser.entity["uacute"] = "ú"
    parser.entity["ucirc"] = "û"
    parser.entity["uuml"] = "ü"

    parser.entity["Yacute"] = "Ý"
    parser.entity["159"] = "Ÿ"
    parser.entity["yacute"] = "ý"
    parser.entity["yuml"] = "ÿ"

    parser.entity["AElig"] = "Æ"
    parser.entity["aelig"] = "æ"
    parser.entity["szlig"] = "ß"
    parser.entity["Ccedil"] = "Ç"
    parser.entity["ccedil"] = "ç"
    parser.entity["Ntilde"] = "Ñ"
    parser.entity["ntilde"] = "ñ"
    parser.entity["Oslash"] = "Ø"
    parser.entity["oslash"] = "ø"
    parser.entity["micro"] = "µ"
    parser.entity["reg"] = "®"
    parser.entity["times"] = "⊗"
    parser.entity["eth"] = "ð"
    parser.entity["ETH"] = "Ð"
    parser.entity["THORN"] = "Þ"
    parser.entity["thorn"] = "þ"

    parser.entity["#131"] = "ƒ"
    parser.entity["#140"] = "Œ"
    parser.entity["#156"] = "œ"
    parser.entity["#138"] = "Š"
    parser.entity["#154"] = "š"
    parser.entity["#181"] = "µ"
    parser.entity["#215"] = "×"

    return parser